import { Component } from '@angular/core';
import { routes } from 'src/app/shared/routes/routes';
import { Vademecum } from '../vademecum';
import { VademecumService } from '../vademecum.service';
import { AuthService } from 'src/app/shared/auth/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-voice-call',
  templateUrl: './voice-call.component.html',
  styleUrls: ['./voice-call.component.scss']
})
export class VoiceCallComponent {
  public routes = routes;
  vademecum: Vademecum = new Vademecum();
  vademecums: Vademecum[] = [];
  validador: boolean = false;
  // identificacion: String;
  //change components
  // medicamentosIndicaciones: { [key: string]: string } = {
  //   'Clinadol Forte': 'Indicaciones para Clinadol Forte',
  //   '(S)-3-(1-metilpirrolidin-2-il)piridina (Nicotina)': 'Antitabaquismo',
  //   '1,3-dimetilxantina (Teofilina)': 'Indicaciones para Teofilina',
  //   '1-(4-metoxibenzoil)-2-pirrilidona (Aniracetam)': 'Indicaciones para Aniracetam',
  //   '1-acetamido-2-pirrolidinona (Piracetam)': 'Indicaciones para Piracetam',
  //   '1-alfa-hidroxicolecalciferol (Alfacalcidol)': 'Indicaciones para Alfacalcidol',
  //   '1-beta-D-ribofuranosiluracilo (Uridina)': 'Indicaciones para Uridina',
  //   '1-butoxi-3-fenoxi-2-propanol (Febuprol)': 'Indicaciones para Febuprol'
  // };
  

  
  onChangeMedicamento() {
    switch (this.vademecum.medicamento) {
      case 'Clinadol Forte':
        this.vademecum.indicaciones = 'Terapeutica analgesica y antiinflamatoria.';
        break;
      case '(S)-3-(1-metilpirrolidin-2-il)piridina (Nicotina)':
        this.vademecum.indicaciones = 'Antitabaquismo';
        break;
        case '1-(4-metoxibenzoil)-2-pirrilidona (Aniracetam)':
        this.vademecum.indicaciones = '  Agente neurotrofico';
        break;
      // Agrega casos para otros medicamentos según sea necesario
      default:
        this.vademecum.indicaciones = '';
    }
  }
  opcionesMedicamentos: string[] = [
    "Clinadol Forte",
    '(S)-3-(1-metilpirrolidin-2-il)piridina (Nicotina)',
  '1,3-dimetilxantina (Teofilina)',
  '1-(4-metoxibenzoil)-2-pirrilidona (Aniracetam)',
  '1-acetamido-2-pirrolidinona (Piracetam)',
  '1-alfa-hidroxicolecalciferol (Alfacalcidol)',
  '1-beta-D-ribofuranosiluracilo (Uridina)',
  '1-butoxi-3-fenoxi-2-propanol (Febuprol)',
  '17-alfa-etinilestradiol (Quinestrol)',
  '17-hidroxicorticosterona (Hidrocortisona)',
  '19-nortestosterona (Nandrolona)',
  '2,5-dimetoxinorefedrina (Metoxamina)',
  '2,6-diamino-4-piperidinopirimidina 1-oxido (Minoxidil)',
  '2-butilamino-1-(4-hidroxifenil)etanol sulfato (Bametano)',
  '2-desoxifenobarbital (Primidona)',
  '2-F-ara-A (Fludarabina)',
  '2-fenil-1,3-propanodiol dicarbamato (Felbamato)',
  '2-hidroxibenzoico acido (Salicilico acido)',
  '2-PAM cloruro (Pralidoxima)',
  '2-piridina aldoxima metilcloruro (Pralidoxima)',
  '21-cloro-11-dihidrobetametasona (Clobetasona)',
  '22-oxoxincaleucoblastina (Vincristina)',
  '3-ciclopentil eter (Quinestrol)',
  '3-hidroxi-L-tirosina (Levodopa)',
  '3-piridincarboxilico acido (Nicotinico acido)',
  '4-amino-5-hexanoico acido (Vigabatrin)',
  '4-amino-6-metoxi-fenilpiridazina metilsulfato (Amezinio)',
  '4-aminobenzenosulfonamida (Sulfanilamida)',
  '4-cloro-N-(2-morfolinoetil)benzamida (Moclobemida)',
  '4-demetoxidaunorrubicina hidroclorhidrato (Idarrubicina)',
  '4-hidroxiandrostenediona (Formestano)',
  '4-OHA (Formestano)',
  '4-OHAD (Formestano)',
  '5-(2,4-diflurofenil)salicilico acido (Diflunisal)',
  '5-acetil-5-metoxitriptamina (Melatonina)',
  '5-ASA (Mesalazina)',
  '5-fluorouracilo (Fluorouracilo)',
  '5-FU (Fluorouracilo)',
  '6MP (Mercaptopurina)',
  '7-isopropoxiisoflavona (Ipriflavona)',
  '8-metoxipsoraleno (Metoxaleno)',
  '8-MOP (Metoxaleno)',
  '9-alfa-flurocortisol (Fludrocortisona)',
  'AAS (Acetilsalicilico acido)',
  'Aceite de castor (Aceite de ricino)',
  'Aceite de palma christi (Aceite de ricino)',
  'Acenocumarina (Acenocumarol)',
  'Aceroxatidina (Roxatidina)',
  'Acetamidohexanoico acido (Acexamico acido)',
  'Acetaminocaproico acido (Acexamico acido)',
  'Acetaminofeno (Paracetamol)',
  'Acetazolam (Acetazolamida)',
  'Acetilaspartilglutamico acido (Isospaglumico acido)',
  'Acetilcarnitina ester (Acetilcarnitina)',
  'Acetilsalicilato de lisina (Lisina acetilsalicilato)',
  'Acexamato de cinc (Acexamico acido)',
  'Acicloguanosina (Aciclovir)',
  'Acido acetoxi 2 benzoico (Acetilsalicilico acido)',
  'Acidos biliares (Sales biliares)',
  'ACTH (Hormona adrenocorticotropica hipofisaria)',
  'Actinomicina D (Dactinomicina)',
  'Actinospectacina (Espectinomicina)',
  'Activador extrinseco del plasminogeno (Alteplasa)',
  'Activador tisular del plasminogeno (Alteplasa)',
  'Adamantano 1 amino (Amantadina)',
  'Ademetionina (Adenosilmetionina)',
  'Adermina hidroclorhidrato (Piridoxina)',
  'Adrenocorticotropina (Hormona adrenocorticotropica hipofisaria)',
  'Adriamicina (Doxorrubicina)',
  'Aesculus hippocastanum L. (Escina)',
  'Afrodina (Yohimbina)',
  'AHB-DBK (Arbekacina)',

  'Albuterol (Salbutamol)',
  'Alcohol pantotenilico (Pantenol)',
  'Aldesleukina (Interleucina 2)',
  'Alendronico acido (Alendronato)',
  'Alfa aminobencilpenicilina (Ampicilina)',
  'Alfa metildopa (Metildopa)',
  'Alfa-clopentixol (Zuclopentixol)',
  'Alfa-hipofamina (Oxitocina)',
  'Alfa-interferon (Interferon alfa)',
  'Algeldrato (Aluminio hidroxido)',
  'Aloperidol (Haloperidol)',
  'Alquildimetilbencilamonio cloruro (Benzalconio cloruro)',
  'Aluminio magnesio hidroxido monohidrato (Magaldrato)',
  'Amcinopol (Amcinonida)',
  'AMD (Metildopa)',
  'Ametocaina (Tetracaina)',
  'Ametopterina (Metotrexato)',
  'Amidotrizoato de calcio (Diatrizoico acido)',
  'Amidotrizoico acido (Diatrizoico acido)',
  'Amilobarbitona (Amobarbital)',
  'Amilorida + hidroclorotiazida (Hidroclorotiazida + amilorida)',
  'Aminometil clorhidrocinamico acido (Baclofeno)',
  'Aminonaftona (Aminaftona)',
  'Aminopropilaminoetiltiofosfato (Amifostina)',
  'Aminosultoprida (Amisulprida)',
  'Amipramidina (Amilorida)',
  'Amiprazida (Amilorida)',
  'Ammoidin (Metoxaleno)',
  'Amonio paramolibdato (Amonio molibdato)',
  'Amudano (Griseofulvina)',
  'Analgina (Dipirona)',
  'Androstanazol (Estanozolol)',
  'Androstanolona (Testosterona)',
  'Aneurina (Tiamina)',
  'Anfebutamona (Bupropion)',
  'Anfepramona (Dietilpropion)',
  'Anfotericina B (Amfotericina B)',
  'Anticuerpo OKT3 (Muromonab CD3)',
  'Antitoxina difterica (Toxoide difterico)',
  'Antitoxina tetanica (Toxoide tetanico)',
  'Antralina (Ditranol)',
  'Aotal (Acamprosato)',
  'Apazona (Azapropazona)',
  'Aplonidina (Apraclonidina)',
  'Aspirina (Acetilsalicilico acido)',
  'AT-7 (Hexaclorofeno)',
  'Autoprotrombina II (Factor IX)',
  'Axeroftol (Vitamina A)',
  'Azacort (Deflazacort)',
  'Azidotimidina (Zidovudina)',
  'Azodisal (Olsalazina)',
  'Azotioprina (Azatioprina)',
  'Azoxodona (Pemolina)',
  'AZT (Zidovudina)',
  'Azucar manna (Manitol)',
  'B-metasona (Betametasona)',
  'Bacitracina + neomicina + polimixina B (Neomicina + polimixina B + bacitracina)',
  'Barbamil (Amobarbital)',
  'Barosmina (Diosmina)',
  'BCNU (Carmustina)',
  'Bencidroflumetiazida (Bendroflumetiazida)',
  'Bencilhidroflumetiazida (Bendroflumetiazida)',
  'Bencilpenicilina G procainica (Penicilina G procainica)',
  'Bencilpenicilina G sodica (Penicilina G sodica)',
  'Bendrofluazida (Bendroflumetiazida)',
  'Benfluramato (Benfluorex)',
  'Benserazida + levodopa (Levodopa + benserazida)',
  'Benzetacil (Penicilina G benzatinica)',
  'Benzhexol clorhidrato (Trihexifenidilo)',
  'Benzoilo superoxido (Benzoilo peroxido)',
  'Benzolin (Dibucaina)',
  'Benzononatina (Benzonatato)',

  'Benzopirona (Cumarina)',
  'Besilato atracurio (Atracurio)',
  'Beta estradiol (Estradiol)',
  'Beta metildigoxina (Digoxina)',
  'Beta metilprednisona acetato (Meprednisona)',
  'Beta-interferon (Interferon beta)',
  'Beta-quinina (Quinidina)',
  'Beta-tiovalina (Penicilamina)',
  'Betaaminoetilimidazol (Histamina)',
  'Betadexametasona (Betametasona)',
  'BiCNU (Carmustina)',
  'Bilis (Sales biliares)',
  'Bilis de buey (Sales biliares)',
  'Bilis de cerdo (Sales biliares)',
  'Bioepiderm (Biotina)',
  'Biosterol (Vitamina A)',
  'Bromoclorotrifluoroetano (Halotano)',
  'Bromofeniramina (Bromfeniramina)',
  'Bromoprofenpiridamina (Bromfeniramina)',
  'Bunolol (Levobunolol)',
  'Butetanol (Tetracaina)',
  'Butilescopolamina (Hioscina butilbromuro)',
  'Butilhioscina (Hioscina butilbromuro)',
  'Butilhioscina + metamizol (Hioscina butilbromuro + dipirona)',
  'Ca (Calcio)',
  'Ca-AOTA (Acamprosato)',
  'Calciferol (Ergocalciferol)',
  'Calcio acetil homotaurinato (Acamprosato)',
  'Calcio ascorbato (Ascorbico acido)',
  'Calcio diatrizoato (Diatrizoico acido)',
  'Calcio difenilhidantoinato (Difenilhidantoina)',
  'Calcio disodico etilendiamintetraacetato (Edetato calcico disodico)',
  'Calcio folinato (Leucovorina calcica)',
  'Calcipotrieno (Calcipotriol)',
  'Carampicilina (Bacampicilina)',
  'Carbacefaclor (Loracarbef)',
  'Carbamida (Urea)',
  'Carbamilcolina clorhidrato (Carbacol)',
  'Carbenoxalona (Carbenoxolona)',
  'Carbidopa + levodopa (Levodopa + carbidopa)',
  'Carbocolina (Carbacol)',
  'Carbofos (Malation)',
  'Carbon adsorbente (Carbon activado)',
  'Carbonildiamida (Urea)',
  'Carboxifosfato trisodico (Foscarnet sodico)',
  'Carboximetilcisteina (Carbocisteina)',
  'Carboxiterfenadina (Fexofenadina)',
  'Carisoprodato (Carisoprodol)',
  'Catalin (Pirenoxina)',
  'CDP colina (Citicolina)',
  'Cetoprofeno (Ketoprofeno)',
  'Cevitamico acido (Ascorbico acido)',
  'Chitosamina (Glucosamina)',
  'Cianocobalamina (Vitamina B12)',
  'Cianocobamida (Vitamina B12)',
  'Ciclofosfano (Ciclofosfamida)',
  'Ciclonamina (Etamsilato)',
  'Ciclopiroxolamina (Ciclopirox)',
  'Cidantina (Hesperidina)',
  'Cilastatina + imipenem (Imipenem + cilastatina)',
  'Ciloprost (Iloprost)',
  'Cinc undecilenato (Undecilenico acido)',
  'Cincocaina (Dibucaina)',
  'Cinipirina (Cinarizina)',
  'Cinoxicam (Piroxicam cinamato acido)',
  'Cis-DDP (Cisplatino)',
  'Cis-diaminodicloroplatino (Cisplatino)',
  'Citidina colindifosfato (Citicolina)',
  'Citidina difosfato colina (Citicolina)',
  'Citofosfano (Ciclofosfamida)',
  'Citosina arabinosido (Citarabina)',
  'Clavulanico acido + amoxicilina (Amoxicilina + acido clavulanico)',
  'Clavulanico acido + ticarcilina (Ticarcilina + acido clavulanico)',
  'Clemizol penicilina (Penicilina G clemizol)',
  'Clodronato disodico (Clodronico acido)',
  'Clonixina (Lisina clonixinato)',
  'Clonixinato de lisina (Lisina clonixinato)',
  'Clopoxida (Clordiazepoxido)',
  'Cloramifeno (Clomifeno citrato)',
  'Cloraminofeno (Clorambucilo)',
  'Clorazepico acido (Clorazepato dipotasico)',
  'Clorazolam (Triazolam)',
  'Cloretiazol (Clometiazol)',
  'Clorfenamina (Clorfeniramina)',
  'Clorhistapiridamina (Clorfeniramina)',
  'Clorimipramina (Clomipramina)',
  'Clormetazanona (Clormezanona)',
  'Clormetiazol (Clometiazol)',
  'Cloroambucilo (Clorambucilo)',
  'Clorodesoxiadenosina (Cladribina)',
  'Clorofenpiridamina (Clorfeniramina)',
  'Cloronautina (Dimenhidrinato)',
  'Clorosultiadil (Hidroclorotiazida)',
  'Clorprofenpiridamina (Clorfeniramina)',
  'Clortenoxicam (Lornoxicam)',
  'Clortrimeton (Clorfeniramina)',
  'Cloruro de potasio (Potasio cloruro)',
  'Clostridiopeptidasa (Colagenasa)',
  'Cobamamida (Vitamina B12)',
  'Coenzima citidilica (Citicolina)',
  'Coenzima R (Biotina)',
  'Colaspasa (Asparaginasa)',
  'Colecalciferol (Calcitriol)',
  'Colextran (Dextran)',
  'Colina CDP (Citicolina)',
  'Conquinina (Quinidina)',
  'Cordiceptico acido (Manitol)',
  'Corinina (Yohimbina)',
  'Corticosterona (Desoximetasona)',
  'Corticotropina (Hormona adrenocorticotropica hipofisaria)',
  'Cortisol (Hidrocortisona)',
  'Cortisona (Hidrocortisona)',
  'Corynanthe yohimbe (Yohimbina)',
  'Cosintropina (Tetracosactida)',
  'Cotrimoxazol (Sulfametoxazol + trimetoprima)',
  'Cr (Cromo)',
  'Crisazina (Dantron)',
  'Cromoglicico acido (Cromoglicato disodico)',
  'CSF-2 (Molgramostim)',
  'CSF-alfa (Molgramostim)',
  'Cyclocort (Amcinonida)',
  'd-2-(6-metoxi-2-naftil)propionico acido (Naproxeno)',
  'D-glucitol (Sorbitol)',
  'D-glutitol (Sorbitol)',
  'D-tubocurarina (Tubocurarina)',
  'Dacliximab (Daclizumab)',
  'Dalfopristina + quinupristina (Quinupristina + dalfopristina)',
  'Daunomicina (Daunorrubicina)',
  'DDAA (Memantina)',
  'DDC (Zalcitabina)',
  'ddCyd (Zalcitabina)',
  'ddI (Didanosina)',
  'ddIno (Didanosina)',
  'DDS (Dapsona)',
  'Debekacina (Dibekacina)',
  'Defenidol (Difenidol)',
  'Deferoxamina (Desferroxamina)',
  'Dehidrobenzoperidol (Droperidol)',
  'Dehidrocolato sodico (Dehidrocolico acido)',
  'Deltaparina (Heparina)',
  'Deprenilo (Selegilina)',
  'Desacetilvinblastina amida (Vindesina)',
  'Desclorobiomicina (Tetraciclina)',
  'Desferoxamina (Desferroxamina)',
  'Desitriptilina (Nortriptilina)',
  'Desmetilamitriptilina (Nortriptilina)',
  'Desmetilimipramina (Desipramina)',
  'Desoxicortona (Desoxicorticosterona)',
  'Detaxtran (Dextran)',
  'Dexbromfeniramina (Bromfeniramina)',
  'Dexpantenol (Pantenol)',
  'Dextrosulfenidol (Tianfenicol)',

  'dFdC (Gemcitabina)',
  'dFdCyd (Gemcitabina)',
  'Diacepin (Diazepam)',
  'Diacetilmidecamicina (Miocamicina)',
  'Diacetoxidifenil metilpiridina (Bisacodilo)',
  'Diafenilsulfona (Dapsona)',
  'Dialilnortoxiferina (Alcuronio cloruro)',
  'Dialiltoxiferina (Alcuronio cloruro)',
  'Diaminodifenilsulfona (Dapsona)',
  'Diaminofenilazopiridina (Fenazopiridina)',
  'Diaminopenicilina (Penicilina G benzatinica)',
  'Diazefonato (Clordiazepoxido)',
  'Dibenzoilo superoxido (Benzoilo peroxido)',
  'DIC (Dacarbazina)',
  'Dicain (Tetracaina)',
  'Dicicloverina (Diciclomina)',
  'Diclofenac potasico (Diclofenac)',
  'Diclofenac sodico (Diclofenac)',
  'Diclometanedifosfonico acido (Clodronico acido)',
  'Dideoxicitidina (Zalcitabina)',
  'Dideoxiinosina (Didanosina)',
  'Dideoxikanamicina B (Dibekacina)',
  'Dietildihidroxiestilbeno difosfato (Fosfestrol)',
  'Dietilestilbestrol difosfato (Fosfestrol)',
  'Digitalin (Digitoxina)',
  'Digitofilina (Digitoxina)',
  'Digoxosida (Digoxina)',
  'Dihidroclorotiazida (Hidroclorotiazida)',
  'Dihidrocodeinona (Hidrocodona)',
  'Dihidroergotamina (Ergotamina)',
  'Dihidroergotixona monometansulfonato (Codergocrina mesilato)',
  'Dihidrofoliculina (Estradiol)',
  'Dihidrohidroxicodeinona (Oxicodona)',
  'Dihidroxiestrina (Estradiol)',
  'Dihidroxifenilalanina (Levodopa)',
  'Dihidroxitalofenona (Fenolftaleina)',
  'Dimeglumina gadopentetato (Gadolinio DTPA)',
  'Dimepirindeno (Dimetindeno maleato)',
  'Dimetil-trizeno-imidazol-carboxamida (Dacarbazina)',
  'Dimetilpolisiloxano (Dimeticona)',
  'Dinitrato de isosorbide (Isosorbide dinitrato)',
  'Dinitrosorbide (Isosorbide dinitrato)',
  'Diosmetina 7-rutinosido (Diosmina)',
  'Dipalmitoil fosfatidilcolina (Colfoscerilo palmitato)',
  'Dipiosteina (Erdosteina)',
  'Dipirona + escopolamina (Hioscina butilbromuro + dipirona)',
  'Dipivalil epinefrina (Dipivefrina)',
  'Disoprofol (Propofol)',
  'Diviminol (Vigabatrin)',
  'Diyodohidroxiquinolina (Yodoquinol)',
  'Diyodooxiquinolina (Yodoquinol)',
  'Diyodoquinolina (Yodoquinol)',
  'DL-hiosciamina (Atropina)',
  'DMC (Penicilamina)',
  'DMGG (Metformina)',
  'DMSO (Dimetilsulfoxido)',
  'Dobesilato calcico (Calcio dobesilato)',
  'DPE (Dipivefrina)',
  'DPPC (Colfoscerilo palmitato)',
  'DTIC (Dacarbazina)',
  'Edatamil calcio disodico (Edetato calcico disodico)',
  'EDTA calcico (Edetato calcico disodico)',
  'Elcatonina (Calcitonina)',
  'EPEG (Etoposido)',
  'Epidoxorrubicina (Epirrubicina)',
  'Epinefrina (Adrenalina)',
  'EPO (Eritropoyetina)',
  'Epoetina (Eritropoyetina)',
  'Eptastatina sodica (Pravastatin)',
  'Ergometrina (Ergonovina)',
  'Ergosterol activado (Ergocalciferol)',
  'Escopolamina butilbromuro (Hioscina butilbromuro)',
  'ESF (Eritropoyetina)',
  'Estanazol (Estanozolol)',
  'Estannoso floruro (Fluoruro estannoso)',
  'Estavudina (Stavudina)',
  'Estradiol + drospirenona (Drospirenona + estradiol)',
  'Estradiol valerato + dienogest (Dienogest + estradiol valerato)',
  'Eter metoxifenilglicerilo (Guaifenesina)',
  'Ethocaina (Procaina)',
  'Etidronato (Etidronico acido)',
  'Etiladrianol (Etilefrina)',
  'Etilfenilefrina (Etilefrina)',
  'Etilo aminobenzoato (Benzocaina)',
  'Etinilestradiol + desogestrel (Desogestrel + etinilestradiol)',
  'Etinilestradiol + dienogest (Dienogest + etinilestradiol)',
  'Etinilestradiol + drospirenona (Drospirenona + etinilestradiol)',
  'Etinilestradiol + levonorgestrel (Levonorgestrel + etinilestradiol)',
  'Etinilestradiol + norelgestromina (Norelgestromina + etinilestradiol)',
  'Etinilestradiol + norgestimato (Norgestimato + etinilestradiol)',
  'Etinilestradiol + norgestrel (Norgestrel + etinilestradiol)',
  'Etiofos (Amifostina)',
  'Etodolico acido (Etodolac)',
  'Etretina (Acitretina)',
  'Euresol (Resorcina)',
  'Factor antihemofilico A (Factor VIII)',
  'Factor antihemofilico B (Factor IX)',
  'Factor de difusion (Hialuronidasa)',
  'Factor hiperglicemico-glicogenolitico (Glucagon)',
  'Factor liberador de tirotrofina (Protirelina)',
  'Factor preventivo de la pelagra (Nicotinico acido)',
  'Factor VIII recombinante (Octocog alfa)',
  'Fe (Hierro)',
  'Fenazona (Antipirina)',
  'Fenazopiridina + sulfametizol (Sulfametizol + fenazopiridina)',
  'Fenfluramina (Dexfenfluramina)',
  'Fenildimetilpirazolona (Antipirina)',
  'Feniletilbarbiturato sodio (Fenobarbital)',
  'Feniletilbarbiturico acido (Fenobarbital)',
  'Fenoxiisopropilnorsuprifeno (Isoxsuprina)',
  'Fenoximetilpenicilinico acido (Fenoximetilpenicilina)',
  'Fenozaxol (Pemolina)',
  'Fibrinolisina (Plasmina)',
  'Fibrinoquinasa (Alteplasa)',
  'FIF (Interferon beta)',
  'Fisalamina (Mesalazina)',
  'Fitonadiona (Fitomenadiona)',
  'Fitoquinona (Fitomenadiona)',
  'Flubenilosolona (Betametasona)',
  'Fluhidrocortisona (Fludrocortisona)',
  'Fluhidrosona (Fludrocortisona)',
  'Flumazepil (Flumazenil)',
  'Fluorocitosina (Flucitosina)',
  'Fluoromebendazol (Flubendazol)',
  'Fluorovidarabina (Fludarabina)',
  'Fluoruro de sodio (Sodio fluoruro)',
  'Flurandrenolida (Fludroxicortida)',
  'Flurandrenolona (Fludroxicortida)',
  'Folinico acido (Leucovorina calcica)',
  'Folitropina (Hormona foliculoestimulante)',
  'Fonazina (Dimetotiazina)',
  'Fosenopril (Fosinopril)',
  'Fosfato de potasio (Potasio fosfato)',
  'Fosfonoformiato trisodico (Foscarnet sodico)',
  'Fosfotion (Malation)',
  'Framicetina (Neomicina)',
  'Frusemida (Furosemida)',
  'FSH (Hormona foliculoestimulante)',
  'Fumarato ferroso (Hierro fumarato)',
  'Furadantina (Nitrofurantoina)',
  'Furazosin (Prazosin)',
  'Fursemida (Furosemida)',
  'Gadopentetico acido (Gadolinio DTPA)',
  'Gamma aminobutirico acido (GABA)',
  'Gamma benceno hexacloruro (Lindano)',
  'Gamma hexaclor (Lindano)',
  'Gamma hexaclorociclohexano (Lindano)',
  'Gamma-interferon (Interferon gamma (1b))',
  'Gamma-vinil GABA (Vigabatrin)',
  'Gammafos (Amifostina)',
  'Gestodeno + etinilestradiol (Etinilestradiol + gestodeno)',
  'Gestronol caproato (Gestonorona)',
  'GH (Somatotropina)',
  'GH-RIF (Somatostatina)',
  'Ginkgo (Ginkgo biloba)',
  'Glibenciclamida (Glibenclamida)',
  'Gliburida (Glibenclamida)',
  'Glicerilguayacolico eter (Guaifenesina)',
  'Glicerilo guayacolato (Guaifenesina)',
  'Glicerilo trinitrato (Nitroglicerina)',
  'Glicerol (Glicerina)',
  'Glicerol yodado (Glicerina yodada)',
  'Glicopirronio bromuro (Glicopirrolato)',
  'Glidiazinamida (Glipizida)',
  'Globulina antihemofilica A (Factor VIII)',
  'Glomicina (Oxitetraciclina)',
  'Glonoina (Nitroglicerina)',
  'Gluconato de calcio (Calcio gluconato)',
  'Glucosa (Dextrosa)',
  'GMCSF (Molgramostim)',
  'Gonadoliberin (Hormona liberadora de gonadotropina (GnRH))',
  'Gonadorrelina (Hormona liberadora de gonadotropina (GnRH))',
  'Gonadotropina corionica alfa (Coriogonadotropina alfa)',
  'Guaiacuran (Guaifenesina)',
  'Guanamprazina (Amilorida)',
  'Guoscopina (Noscapina)',
  'GVG (Vigabatrin)',
  'HABA-Dibekacina (Arbekacina)',
  'HCG (Gonadotropina corionica humana)',
  'Hemopoyetina (Eritropoyetina)',
  'Heparinico acido (Heparina)',
  'Hesperetina-7-rutinosido (Hesperidina)',
  'Hexadecadrol (Dexametasona)',
  'Hexadecilfosfocolina (Miltefosina)',
  'Hexametilenamina (Metenamina)',
  'Hexametilentetramina canfosulfonato (Metenamina)',
  'Hexametilmelamina (Altretamina)',
  'Hexamina salicilato (Metenamina)',
  'HG-factor (Glucagon)',
  'HGF (Glucagon)',
  'Hialuronato sodico (Sodio hialuronato)',
  'Hialuronico acido (Sodio hialuronato)',
  'Hicamptamina (Topotecan)',
  'Hidrato de hormona folicular (Estriol)',
  'Hidrazinoftalazina (Hidralazina)',
  'Hidroclorotiazida + triamtereno (Triamtereno + hidroclorotiazida)',
  'Hidroquinol (Hidroquinona)',
  'Hidroquinona calcio sulfonato (Calcio dobesilato)',
  'Hidroretrocortina (Prednisolona)',
  'Hidroxicarbamida (Hidroxiurea)',
  'Hidroxietil rutosidos (Troxerutina)',
  'Hidroximetilcelulosa (Hidroxipropilmetilcelulosa)',
  'Hidroxipolietoxidodecano (Polidocanol)',
  'Hidroxitetraclicina (Oxitetraciclina)',
  'Hidroxocobalamina (Vitamina B12)',
  'Hiedra extracto (Hedera helix)',
  'Hiosciamina (Atropina)',
  'Hioscina butilbromuro + metamizol (Hioscina butilbromuro + dipirona)',
  'Hipoxantina ribosida (Inosina)',
  'Hipoxantosina (Inosina)',
  'Hipromelosa (Hidroxipropilmetilcelulosa)',
  'Histabutizina (Buclizina)',
  'HMT (Metenamina)',
  'Hormona antiinflamatoria (Hidrocortisona)',
  'Hormona dihidrofolicular (Estradiol)',
  'Hormona somatotropica (Somatotropina)',
  'HPC (Miltefosina)',
  'HPMC (Hidroxipropilmetilcelulosa)',
  'Hypericum perforatum L. (Hiperico)',
  'Ibenzmetizina (Procarbazina)',
  'Ibidomida (Labetalol)',
  'IFN-alfa (Interferon alfa)',
  'IFN-beta (Interferon beta)',
  'IFN-gamma (Interferon gamma (1b))',
  'IL-2 (Interleucina 2)',
  'Imidazolina (Nafazolina)',
  'ImIFN (Interferon gamma (1b))',
  'Imipemida (Imipenem)',
  'Imizin (Imipramina)',
  'Indometacina glucosamida (Glucametacina)',
  'INH (Isoniazida)',
  'Inmuno IFN (Interferon gamma (1b))',
  'Interferon fibroblastico (Interferon beta)',
  'Interferon leucocitario (Interferon alfa)',
  'Interferon linfoblastoide (Interferon alfa)',
  'Interferon tipo II (Interferon gamma (1b))',
  'Iobitridol (Yobitridol)',
  'Iohexol (Yohexol)',
  'Iopamidol (Yopamidol)',
  'Iopanoico acido (Yopanoico acido)',
  'Iproveratrilo (Verapamilo)',
  'Isobamato (Carisoprodol)',
  'Isoefedrina (Efedrina)',
  'Isoendoxan (Ifosfamida)',
  'Isofosfamida (Ifosfamida)',
  'Isonicotinilhidrazina (Isoniazida)',
  'Isonicotinoilhidrazina (Isoniazida)',
  'Isonipeicaina (Meperidina)',
  'Isoprenalina (Isoproterenol)',
  'Isopropilarterenol (Isoproterenol)',
  'Isopropilo meprobamato (Carisoprodol)',
  'Isosorbide mononitrato (Isosorbide 5-mononitrato)',
  'Isrodipina (Isradipina)',
  'Jinofloxacina (Nadifloxacina)',
  'Keoxifeno (Raloxifeno)',
  'KPABA (Potasio aminobenzoato)',
  'L-5-hidroxitriptan (Oxitriptan)',
  'L-5HTP (Oxitriptan)',
  'L-arginina (Arginina)',
  'L-asnasa (Asparaginasa)',
  'L-asparagina amidohidrolasa (Asparaginasa)',
  'L-asparaginasa (Asparaginasa)',
  'L-carnitina (Carnitina)',
  'L-cisteina (Cisteina)',
  'L-Dopa (Levodopa)',
  'L-sarcolisina (Melfalan)',
  'L-tetramisol hidroclorhidrato (Levamisol)',
  'L-xyloascorbico acido (Ascorbico acido)',
  'Lactit (Lactitol)',
  'Lactitelactobiosit (Lactitol)',
  'Lactoflavina (Riboflavina)',
  'Lactosit (Lactitol)',
  'Lactositol (Lactitol)',
  'Laevo-dopa (Levodopa)',
  'Latiazem (Diltiazem)',
  'Lauret 9 (Polidocanol)',
  'LCR (Vincristina)',
  'LeIF (Interferon alfa)',
  'Lepargilico acido (Azelaico acido)',
  'Leucocristina (Vincristina)',
  'Leucomicina A3 (Josamicina)',
  'Leucotrofina (Timomodulina)',
  'Leukaemomicina C (Daunorrubicina)',
  'Leuprorelina (Leuprolide acetato)',
  'Levoprazina (Levomepromazina)',
  'LH RH (Hormona liberadora de gonadotropina (GnRH))',
  'LH-RF (Hormona liberadora de gonadotropina (GnRH))',
  'Lignocaina (Lidocaina)',
  'Lincolnensina (Lincomicina)',
  'Liotironina (Triyodotironina)',
  'LRF (Hormona liberadora de gonadotropina (GnRH))',
  'LRH (Hormona liberadora de gonadotropina (GnRH))',
  'Luliberin (Hormona liberadora de gonadotropina (GnRH))',
  'Luteohormona (Progesterona)',
  'M-dihidroxibenceno (Resorcina)',
  'M-hidroxifenilpropanolamina (Metaraminol)',
  'M-hidroxinorefedrina (Metaraminol)',
  'M-hidroxipropadrina (Metaraminol)',
  'Macrogol nonilfenil eter (Nonoxinol)',
  'Madeliltropina (Homatropina)',
  'Magnesia (Magnesio oxido)',
  'Magnesio carbonato hidroxido (Hidrotalcita)',
  'Magnesio pemolina (Pemolina)',
  'Manganeso dicloruro (Magnesio cloruro)',
  'Mannite (Manitol)',
  'Mebubarbital (Pentobarbital)',
  'Meclastina (Clemastina)',
  'Medigoxina (Metildigoxina)',
  'Mefenamina (Orfenadrina)',
  'Mefobarbital (Fenobarbital)',
  'Mepifilina (Mepiramina)',
  'Mepirodipina (Barnidipino)',
  'Mepromazina (Levomepromazina)',
  'Mercaptoetil sulfonato sodico (Mesna)',
  'Mercaptotion (Malation)',
  'Mercazolil (Metimazol)',
  'Mesalamina (Mesalazina)',
  'Metacortandracin (Prednisona)',
  'Metaminodiazepoxido (Clordiazepoxido)',
  'Metamizol (Dipirona)',
  'Metamizol + butilhioscina (Hioscina butilbromuro + dipirona)',
  'Metamizol + escopolamina (Hioscina butilbromuro + dipirona)',
  'Metampirona (Dipirona)',
  'Metanosulfonato sodico (Dipirona)',
  'Metaoxedrina (Fenilefrina)',
  'Metaproterenol (Orciprenalina)',
  'Metaradrina (Metaraminol)',
  'Metazolastona (Temozolomida)',
  'Metil lorazepam (Lormetazepam)',
  'Metil-sulfoxido (Dimetilsulfoxido)',
  'Metilacetoxiprogesterona (Medroxiprogesterona)',
  'Metilamino etanolfenol hidroclorhidrato (Fenilefrina)',
  'Metilaminopterina (Metotrexato)',
  'Metilatropina (Atropina)',
  'Metildiazepinona (Diazepam)',
  'Metilergobasina (Metilergonovina)',
  'Metilergol carbamida (Lisurida)',
  'Metilfenidan (Metilfenidato)',
  'Metilflureter (Enflurano)',
  'Metilmelubrina (Dipirona)',
  'Metilmorfina (Codeina)',
  'Metilpartricina (Mepartricina)',
  'Metilpolisiloxano (Simeticona)',
  'Metilprednisona (Meprednisona)',
  'Metilteobromina (Cafeina)',
  'Metipregnona (Medroxiprogesterona)',
  'Metotrimeprazina (Levomepromazina)',
  'Metoxi 3N metilmorfina (Dextrometorfano)',
  'Metoxidrastina (Noscapina)',
  'Metrogestona (Medrogestona)',
  'Mevinolin (Lovastatin)',
  'Midalcipran (Milnacipran)',
  'Midriatin (Fenilpropanolamina)',
  'Minoxidilo (Minoxidil)',
  'MNPA (Naproxeno)',
  'Mofetil micofenolato (Micofenolato mofetilo)',
  'Monosulfiram (Sulfiram)',
  'Morfia (Morfina)',
  'Moroctocog (Factor VIII)',
  'Morsidomina (Molsidomina)',
  'Mucilago de llanten (Plantago psyllium)',
  'N-dimetilguanilguanidina (Metformina)',
  'N-acetilaspartilglutamico acido (Isospaglumico acido)',
  'N-allilnoroximorfona (Naloxona)',
  'N-bencil-2-nitro-1-imidazolacetamida (Benznidazol)',
  'N-butilbromuro de hioscina (Hioscina butilbromuro)',
  'N-formidoiltienamicina monohidrato (Imipenem)',
  'N-isopropilnoradrenalina (Isoproterenol)',
  'N-isopropilnoratropina bromometilato (Ipratropio bromuro)',
  'Nafronil (Naftidrofurilo)',
  'Naftifungin (Naftifina)',
  'Naftiomato (Tolnaftato)',
  'Naftoquinona (Naftazona)',
  'Nalidixinico acido (Nalidixico acido)',
  'Narbivolol (Nebivolol)',
  'Narcosina (Noscapina)',
  'Narcotina clorhidrato (Noscapina)',
  'Nebramicina factor 6 (Tobramicina)',
  'Neosinefrina (Fenilefrina)',
  'NF 6 (Tobramicina)',
  'Niacina (Nicotinico acido)',
  'Niacinamida (Vitamina B3)',
  'Nicotergolina (Nicergolina)',
  'Nicotinamida (Vitamina B3)',
  'Nicumalona (Acenocumarol)',
  'Niftolida (Flutamida)',
  'Nimergolina (Nicergolina)',
  'Nitalapram (Citalopram)',
  'Nitrimidazina (Nimorazol)',
  'Nitrofural (Nitrofurazona)',
  'Nitrofurazolidona (Furazolidona)',
  'Nitroglicerol (Nitroglicerina)',
  'Nonacog alfa (Factor IX recombinante)',
  'Nonanedioico acido (Azelaico acido)',
  'Nonilfenoxipolietoxietanol (Nonoxinol)',
  'Noramidopiridina (Dipirona)',
  'Norefedrina clorhidrato (Fenilpropanolamina)',
  'Noretindrona (Noretisterona)',
  'Norimipramina (Desipramina)',
  'Notoxin (Procaina)',
  'Novaminsulfonato sodico (Dipirona)',
  'Novocaina (Procaina)',
  'O-carboxifenilfosfato (Fosfosal)',
  'Ocitocina (Oxitocina)',
  'Oestriol (Estriol)',
  'OKT3 (Muromonab CD3)',
  'Oktadin (Guanetidina)',
  'Oktatezin (Guanetidina)',
  'Oleovitamina A (Vitamina A)',
  'Oleovitamina D2 (Ergocalciferol)',
  'Opian (Noscapina)',
  'Opianina (Noscapina)',
  'Oriconazol (Itraconazol)',
  'Orlipastat (Orlistat)',
  'Oxacarbazepina (Oxcarbazepina)',
  'Oxalato platino (Oxaliplatino)',
  'Oxaminozolina (Rilmenidina)',
  'Oxazacort (Deflazacort)',
  'Oxazocilina (Oxacilina)',
  'Oxibutinina hidroclorhidrato (Oxibutinina)',
  'Oxiclorocina (Hidroxicloroquina)',
  'Oxicloroquina (Hidroxicloroquina)',
  'Oxido de cinc (Cinc)',
  'Oxipentifilina (Pentoxifilina)',
  'P-acetamidofenol (Paracetamol)',
  'P-acetaminofenol (Paracetamol)',
  'P-acetilaminofenol (Paracetamol)',
  'P-aminobenzenosulfonoacetamida (Sulfacetamida)',
  'P-aminoclonidina (Apraclonidina)',
  'P-anilinesulfonamida (Sulfanilamida)',
  'P-hidroxiacetanilida (Paracetamol)',
  'P-hidroxiampicilina (Amoxicilina)',
  'P-isobutilhidratropico acido (Ibuprofeno)',
  'P-sulfoamidoalinina (Sulfanilamida)',
  'Palmito salvaje (Serenoa repens)',
  'Pamidronico acido (Pamidronato disodico)',
  'Pancrelipasa (Pancreolipasa)',
  'Pantotenilol (Pantenol)',
  'Pantotenol (Pantenol)',
  'Paraaminobenzoato 2-dietilaminoetil (Procaina)',
  'Paracarbinoxamina (Carbinoxamina)',
  'Paraclorometaxilenol (Cloroxilenol)',
  'Pargeverina (Propinoxato)',
  'Pariprazol (Rabeprazol)',
  'Partricina metil ester (Mepartricina)',
  'Penicianico acido sulfona (Sulbactam)',
  'Penicilanico acido 1,1-dioxido (Sulbactam)',
  'Penicilina V (Fenoximetilpenicilina)',
  'Pentimal (Amobarbital)',
  'Pentiobarbital sodico (Tiopental)',
  'Pentobarbiton (Pentobarbital)',
  'Periciazina (Propericiazina)',
  'Petidina (Meperidina)',
  'PGE-2 (Dinoprostona)',
  'Picosulfato sodico (Sodio picosulfato)',
  'Picosulful (Sodio picosulfato)',
  'Pidorubicina (Epirrubicina)',
  'Pigeum (Pygeum africanum)',
  'Pinol hidrato (Sobrerol)',
  'Pipecuronio bromuro (Pancuronio bromuro)',
  'Piperamico acido (Pipemidico acido)',
  'Piperidico acido (GABA)',
  'Piranisamina (Mepiramina)',
  'Pirazina carboxilamida (Pirazinamida)',
  'Pirazincarboxamida (Pirazinamida)',
  'Pirazinoico acido amida (Pirazinamida)',
  'Pirfenoxona (Pirenoxina)',
  'Piridio (Fenazopiridina)',
  'Piridoxal fosfato (Piridoxina)',
  'Pirilamina (Mepiramina)',
  'Pirimetamina + sulfadoxina (Sulfadoxina + pirimetamina)',
  'Pirisuccideanol (Pirisudanol)',
  'Piritioxina (Piritinol)',
  'Piroleñoso acido (Acetico acido)',
  'Pistocaina (Hidroxipropilmetilcelulosa)',
  'Pitayina (Quinidina)',
  'Pizotifan (Pizotifeno)',
  'Pizotilina (Pizotifeno)',
  'Plasminoquinasa (Estreptoquinasa)',
  'Podofilotoxina (Podofilox)',
  'Podofolinico acido lactona (Podofilox)',
  'Polidimetilsiloxano (Dimeticona)',
  'Polimixina B + neomicina + bacitracina (Neomicina + polimixina B + bacitracina)',
  'Polividona yodada (Povidona yodada)',
  'Polivinilpirrolidona yodada (Povidona yodada)',
  'Ponsinomicina (Miocamicina)',
  'Potaba (Potasio aminobenzoato)',
  'Potasio clavulanato (Clavulanico acido)',
  'Potasio guayacolsulfonato (Sulfoguayacol)',
  'Potasio paraaminobenzoato (Potasio aminobenzoato)',
  'Pramocaina (Pramoxina)',
  'Prednacinolona (Desonida)',
  'Prenazona (Feprazona)',
  'Primaricin (Natamicina)',
  'Proazamina (Prometazina)',
  'Procalmadiol (Meprobamato)',
  'Procalmidol (Meprobamato)',
  'Procetofenico ester (Fenofibrato)',
  'Procetofeno (Fenofibrato)',
  'Profeniramina (Feniramina)',
  'Profenpiridamina (Feniramina)',
  'Proheptatrieno (Ciclobenzaprina)',
  'Propanotriol (Glicerina)',
  'Propin oxifenil mandelato dimetilamonio etano (Propinoxato)',
  'Propinox clorhidrato (Propinoxato)',
  'Propitocaina (Prilocaina)',
  'Propoxifeno (Dextropropoxifeno)',
  'Propranolol (Propanolol)',
  'Proserina (Neostigmina)',
  'Prostaciclina (Epoprostenol)',
  'Prostaglandina E1 (Alprostadil)',
  'Prostaglandina E2 (Dinoprostona)',
  'Prostaglandina I2 (Epoprostenol)',
  'Prostaglandina X (Epoprostenol)',
  'Protogen A (Tioctico acido)',
  'Provitamina A (Beta caroteno)',
  'Proxazocaina (Pramoxina)',
  'Proximetacaina (Proparacaina)',
  'Pseudoefedrina (Seudoefedrina)',
  'Psyllium (Plantago psyllium)',
  'PTC (Factor IX)',
  'Quebrachine (Yohimbina)',
  'Quinol (Hidroquinona)',
  'Ramicin (Fusidico acido)',
  'Ranitidina bismutrex (Ranitidina)',
  'Ranosilhipoxantina (Inosina)',
  'RAPA (Sirolimus)',
  'Rapamicina (Sirolimus)',
  'Razoxano (Dexrazoxano)',
  'Resorcinol (Resorcina)',
  'Retinoico acido (Tretinoina)',
  'Retinol (Vitamina A)',
  'Retrocortina (Prednisona)',
  'rG-CSF (Lenograstim)',
  'rHu-CSF (Lenograstim)',
  'rHu-EPO (Eritropoyetina)',
  'Ricinoleico triglicerido acido (Aceite de ricino)',
  'Ridinol (Pridinol)',
  'Rifampina (Rifampicina)',
  'Rimitzida (Isoniazida)',
  'Riomixina (Oxitetraciclina)',
  'Risedronico acido (Risedronato)',
  'Romglizona (Troglitazona)',
  'RPM (Sirolimus)',
  'Rubidomicina (Daunorrubicina)',
  'S-RIF (Somatostatina)',
  'Sabal serrulata (Serenoa repens)',
  'Salicilato dietilamina (Dietilamina salicilato)',
  'Salicilfosfato (Fosfosal)',
  'SAMe (Adenosilmetionina)',
  'San Juan hierba (Hiperico)',
  'Seroalbumina humana (Albumina humana)',
  'Seudomonico acido (Mupirocina)',
  'Sinstigmina (Neostigmina)',
  'Sinvinolin (Simvastatin)',
  'Sodio calcio edetato (Edetato calcico disodico)',
  'Sodio cromoglicato (Cromoglicato disodico)',
  'Sodio deshidrocolato (Dehidrocolico acido)',
  'Sodio diatrizoato (Diatrizoico acido)',
  'Sodio edetato (Edetato calcico disodico)',
  'Sodio fenildimetilpirazolometilamino benzoato (Propinoxato)',
  'Sodio fusidato (Fusidico acido)',
  'Sodio nitroprusiato (Nitroprusiato sodico)',
  'Sodio undecilenato (Undecilenico acido)',
  'Somatropina (Somatotropina)',
  'Sorbit (Sorbitol)',
  'SRIF-14 (Somatostatina)',
  'Staphylococcus aureus (Vacuna antiestafilococica)',
  'STH (Somatotropina)',
  'Suero antibotulinico (Onabotulinumtoxin A)',
  'Sulbactam + amoxicilina (Amoxicilina + sulbactam)',
  'Sulbactam + ampicilina (Ampicilina + sulbactam)',
  'Sulfafurazol (Sulfisoxazol)',
  'Sulfanilamido 2 pirimidina (Sulfadiazina)',
  'Sulfapirimidina (Sulfadiazina)',
  'Sulfasalazina (Salazosulfapiridina)',
  'Sulfato ferroso (Hierro sulfato)',
  'Sulfinilbismetano (Dimetilsulfoxido)',
  'Surfactante pulmonar modificado (Colfoscerilo palmitato)',
  'Sutoprofeno (Suprofeno)',
  'Suxametonio (Succinilcolina)',
  'T-3 (Triyodotironina)',
  'T-4 (Levotiroxina sodica)',
  't-PA (Alteplasa)',
  'Talamodina (Clortalidona)',
  'Talamudina (Clortalidona)',
  'Taxol (Paclitaxel)',
  'Tazobactam + piperacilina (Piperacilina + tazobactam)',
  'TCA (Calcitonina)',
  'TCGF (Interleucina 2)',
  'TCT (Calcitonina)',
  'Teclosina (Teclozan)',
  'Tedelparina (Dalteparina sodica)',
  'Teicomicina A2 (Teicoplanina)',
  'Tenecetin (Natamicina)',
  'Teofilamina (Aminofilina)',
  'Teofilina etilendiamina (Aminofilina)',
  'Teprubicina (Pirarrubicina)',
  'Terapirol (Dipirona)',
  'Teroilglutamico acido (Folico acido)',
  'Terramicina (Oxitetraciclina)',
  'TESPA (Tiotepa)',
  'Tetraciclinemetino lisina (Limeciclina)',
  'Tetracosactrina (Tetracosactida)',
  'Tetraetiltiuram disulfato (Disulfiram)',
  'Tetrahidropiranil-doxorrubicina (Pirarrubicina)',
  'Tetrametileno bis metansulfonato (Busulfan)',
  'Tetrizolina (Tetrahidrozolina)',
  'Teturamin (Disulfiram)',
  'THP-adriamicina (Pirarrubicina)',
  'THP-doxorrubicina (Pirarrubicina)',
  'Tiamazol (Metimazol)',
  'Tiamina disulfuro (Sulbutiamina)',
  'Timoxamina (Moxisilita)',
  'Tiocolchicina (Tiocolchicosido)',
  'Tiocondramina (Glucosamina)',
  'Tiomebumal sodico (Tiopental)',
  'Tionembumal (Tiopental)',
  'Tiopentona sodica (Tiopental)',
  'Tioserina (Cisteina)',
  'Tirocalcitonina (Calcitonina)',
  'Tiroxina (Levotiroxina sodica)',
  'Toglibutamida (Tolbutamida)',
  'Tolrestatin (Tolrestato)',
  'Torsemida (Torasemida)',
  'Totalbutamida (Tolbutamida)',
  'TP-1 (Timoestimulina)',
  'TPA (Alteplasa)',
  'Transeudomonico acido (Mupirocina)',
  'Treptorelin (Triptorelina)',
  'Treptorrelina (Triptorelina)',
  'Triaconazol (Terconazol)',
  'Tribavirina (Ribavirina)',
  'Trietileno fosforamida (Tiotepa)',
  'Trifluorotimidina (Trifluridina)',
  'Trihidroxietil rutosido (Troxerutina)',
  'Trihidroxipropano (Glicerina)',
  'Trilofosfamida (Trofosfamida)',
  'Trimetilxantina (Cafeina)',
  'Trimetoprima + sulfametoxazol (Sulfametoxazol + trimetoprima)',
  'Trimexolona (Rimexolona)',
  'Trinitrato de glicerilo (Nitroglicerina)',
  'Trinitrina (Nitroglicerina)',
  'Trinitroglicerina (Nitroglicerina)',
  'Trioxietil rutina (Troxerutina)',
  'Trisolareno (Trioxsaleno)',
  'Tropina mandelato (Homatropina)',
  'Tropina tropato (Atropina)',
  'Tsiklomitsin (Tetraciclina)',
  'TSPA (Tiotepa)',
  'TTD (Disulfiram)',
  'Tubazida (Isoniazida)',
  'Uracil ribosida (Uridina)',
  'Urofolitropina (Hormona foliculoestimulante)',
  'Ursodiol (Ursodesoxicolico acido)',
  'Vacuna antitetanica (Toxoide tetanico)',
  'Valeriana officinalis L. (Valeriana)',
  'Valproato de magnesio (Magnesio valproato)',
  'Vazofirina (Pentoxifilina)',
  'VCR (Vincristina)',
  'VDS (Vindesina)',
  'Versenato calcico disodico (Edetato calcico disodico)',
  'Vinagre (Acetico acido)',
  'Vincaleucoblastina (Vinblastina)',
  'Viosterol (Ergocalciferol)',
  'Vitamina A acida (Tretinoina)',
  'Vitamina A alcohol (Vitamina A)',
  'Vitamina A1 (Vitamina A)',
  'Vitamina antipelagra (Nicotinico acido)',
  'Vitamina antixeroftalmica (Vitamina A)',
  'Vitamina B (Complejo vitaminico B)',
  'Vitamina B1 (Tiamina)',
  'Vitamina B2 (Riboflavina)',
  'Vitamina B6 (Piridoxina)',
  'Vitamina B9 (Folico acido)',
  'Vitamina C (Ascorbico acido)',
  'Vitamina D (Ergocalciferol)',
  'Vitamina D-T-acetato (Acetilcarnitina)',
  'Vitamina D2 (Ergocalciferol)',
  'Vitamina D3 (Calcitriol)',
  'Vitamina E (Alfa tocoferol)',
  'Vitamina E natural (Alfa tocoferol)',
  'Vitamina G (Riboflavina)',
  'Vitamina H (Biotina)',
  'Vitamina K (Fitomenadiona)',
  'Vitamina PP (Vitamina B3)',
  'VLB (Vinblastina)',
  'VP-16 (Etoposido)',
  'Xantotoxina (Metoxaleno)',
  'Xilocaina (Lidocaina)',
  'Yodoclorhidroxiquina (Clioquinol)',
  'Yodoclorhidroxiquinoleina (Clioquinol)',
  'Yodocloroxiquinoleina (Clioquinol)',
  'Yodocondramina (Glucosamina)',
  'Yodopovidona (Povidona yodada)',
  'Yodopropilidenglicerol (Glicerina yodada)',
  'Yopaminoico acido (Yopanoico acido)',
  'Zinc (Cinc)',

  ];
  medicamentoFilter: string = '';

  get medicamentosFiltrados(): string[] {
    return this.opcionesMedicamentos.filter(opcion =>
      opcion.toLowerCase().includes(this.medicamentoFilter.toLowerCase())
    );
  }

  // Método para manejar cambios en el cuadro de búsqueda
  onSearchChange(event: any): void {
    this.medicamentoFilter = event.target.value;
  }

  constructor(private auth: AuthService, private doctorService: VademecumService, private router: Router) { }

  ngOnInit(): void {
    this.obtenerpersona();

  }

  obtenerpersona() {
    this.doctorService.obtenerListaPersona().subscribe(dato => {
      this.vademecums = dato;
    });
  }

 

  guardardoctor() {
    console.log(this.vademecum); // Verificar los valores de los campos

    var nombre = this.vademecum.medicamento;
    var laboratorio = this.vademecum.laboratorio;
    var clavesecreta = this.vademecum.composicion;
    var comentarios = this.vademecum.indicaciones;
    var direccion = this.vademecum.contraindicaciones;
    var especialidad = this.vademecum.posologia;
    var telefono = this.vademecum.equivalencias;
    var clave = this.vademecum.anotaciones;
    var notaAuto = this.vademecum.stock;

  
   





    // Código para guardar la persona
    this.doctorService.registrarPersona(this.vademecum).subscribe(dato => {
      this.obtenerpersona();
    }, error => {

      console.log(error);
      alert('La persona ha sido guardada correctamente');

      // Llamada al método para obtener la lista de personas después de guardar una nueva persona
    },

    );

    this.vademecum.medicamento = '';
    this.vademecum.laboratorio = '';
    this.vademecum.composicion = '';
    this.vademecum.indicaciones = '';
    this.vademecum.contraindicaciones = '';
    this.vademecum.posologia = '';
    this.vademecum.equivalencias = '';
    this.vademecum.anotaciones = '';
    this.vademecum.stock = 0;
   
   

  }



  onSubmit() {
    this.guardardoctor();
  }
}
